/* Generated by Yosys 0.9+2406 (git sha1 bd2ecc2d, gcc 11.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "ex4.v:1.1-67.10" *)
module vending(clk, rst, coin_10, coin_50, item, change);
  (* src = "ex4.v:7.5-10.8" *)
  wire [6:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  (* src = "ex4.v:1.76-1.82" *)
  output [6:0] change;
  (* src = "ex4.v:1.22-1.25" *)
  input clk;
  (* src = "ex4.v:1.32-1.39" *)
  input coin_10;
  (* src = "ex4.v:1.41-1.48" *)
  input coin_50;
  (* src = "ex4.v:1.57-1.61" *)
  output item;
  (* src = "ex4.v:3.17-3.26" *)
  (* unused_bits = "1 2 3 4 5 6" *)
  wire [6:0] nextstate;
  (* src = "ex4.v:1.27-1.30" *)
  input rst;
  (* src = "ex4.v:2.17-2.22" *)
  wire [6:0] state;
  assign _028_ = state[5] & state[4];
  assign _029_ = ~(state[5] & state[4]);
  assign _030_ = state[2] | state[3];
  assign _031_ = ~(_030_ | _029_);
  assign _032_ = _028_ & ~(_031_);
  assign _033_ = _032_ | state[6];
  assign _034_ = state[1] & ~(_030_);
  assign _035_ = _029_ | state[6];
  assign _036_ = _034_ & ~(_035_);
  assign item = _036_ | _033_;
  assign change[1] = item & ~(state[1]);
  assign _037_ = state[2] ^ state[1];
  assign change[2] = item & ~(_037_);
  assign _038_ = state[2] | state[1];
  assign _039_ = _038_ ^ state[3];
  assign change[3] = item & ~(_039_);
  assign _040_ = ~(_038_ | state[3]);
  assign _041_ = _040_ ^ state[4];
  assign change[4] = item & ~(_041_);
  assign _042_ = ~(state[3] & state[4]);
  assign _043_ = state[3] | ~(state[4]);
  assign _044_ = _038_ & ~(_043_);
  assign _045_ = _042_ & ~(_044_);
  assign _046_ = _045_ ^ state[5];
  assign change[5] = item & ~(_046_);
  assign _047_ = state[5] & ~(_045_);
  assign _048_ = _047_ ^ state[6];
  assign change[6] = item & ~(_048_);
  assign _049_ = ~rst;
  assign _050_ = coin_50 & coin_10;
  assign _051_ = state[2] | ~(state[3]);
  assign _052_ = _051_ | state[1];
  assign _053_ = state[4] | ~(state[5]);
  assign _054_ = _053_ | state[6];
  assign _055_ = _054_ | _052_;
  assign _056_ = ~(state[2] & state[3]);
  assign _057_ = state[1] & ~(_056_);
  assign _058_ = state[5] | ~(state[4]);
  assign _059_ = _058_ | state[6];
  assign _060_ = _057_ & ~(_059_);
  assign _061_ = _055_ & ~(_060_);
  assign _062_ = state[3] | ~(state[2]);
  assign _063_ = _062_ | state[1];
  assign _064_ = _063_ | _059_;
  assign _065_ = state[1] & ~(_051_);
  assign _066_ = state[5] | state[4];
  assign _067_ = _066_ | state[6];
  assign _068_ = _067_ | ~(_065_);
  assign _069_ = ~(_068_ & _064_);
  assign _070_ = _061_ & ~(_069_);
  assign _071_ = _055_ | _050_;
  assign _072_ = ~(coin_50 & coin_10);
  assign _073_ = _060_ & ~(_072_);
  assign _074_ = _071_ & ~(_073_);
  assign _075_ = ~_050_;
  assign _076_ = _075_ & ~(_064_);
  assign _077_ = _065_ & ~(_067_);
  assign _078_ = _077_ & ~(_072_);
  assign _079_ = _078_ | _076_;
  assign _080_ = _074_ & ~(_079_);
  assign _081_ = _070_ ? _050_ : _080_;
  assign _082_ = _081_ | item;
  assign _000_[1] = _049_ & ~(_082_);
  assign _083_ = _072_ | _055_;
  assign _084_ = _076_ | _077_;
  assign _085_ = _083_ & ~(_084_);
  assign _086_ = _070_ ? _072_ : _085_;
  assign _087_ = _086_ | item;
  assign _000_[2] = _049_ & ~(_087_);
  assign _088_ = coin_50 | ~(coin_10);
  assign _089_ = _050_ | ~(_088_);
  assign _090_ = ~_089_;
  assign _091_ = _059_ | ~(_057_);
  assign _092_ = _089_ ? _091_ : _055_;
  assign _006_ = coin_10 & ~(coin_50);
  assign _093_ = _064_ | ~(_006_);
  assign _001_ = _068_ | _089_;
  assign _002_ = ~(_001_ & _093_);
  assign _003_ = _092_ & ~(_002_);
  assign _004_ = _070_ ? _090_ : _003_;
  assign _005_ = _004_ | item;
  assign _000_[3] = _049_ & ~(_005_);
  assign _007_ = _006_ | _091_;
  assign _008_ = _007_ & _071_;
  assign _009_ = _089_ & ~(_064_);
  assign _010_ = _075_ & ~(_068_);
  assign _011_ = _010_ | _009_;
  assign _012_ = _008_ & ~(_011_);
  assign _013_ = _070_ ? _006_ : _012_;
  assign _014_ = _013_ | item;
  assign _000_[4] = _049_ & ~(_014_);
  assign _015_ = _089_ & ~(_055_);
  assign _016_ = _006_ & ~(_091_);
  assign _017_ = _016_ | _015_;
  assign _018_ = _001_ & ~(_017_);
  assign _019_ = _070_ ? _006_ : _018_;
  assign _020_ = _019_ | item;
  assign _000_[5] = _049_ & ~(_020_);
  assign _021_ = ~(_006_ | _055_);
  assign _022_ = _007_ & ~(_021_);
  assign _023_ = ~(_006_ | _064_);
  assign _024_ = _023_ | _078_;
  assign _025_ = _022_ & ~(_024_);
  assign _026_ = _025_ | _070_;
  assign _027_ = _026_ | item;
  assign _000_[6] = _049_ & ~(_027_);
  reg \state_reg[1] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[1]  <= _000_[1];
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[2]  <= _000_[2];
  assign state[2] = \state_reg[2] ;
  reg \state_reg[3] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[3]  <= _000_[3];
  assign state[3] = \state_reg[3] ;
  reg \state_reg[4] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[4]  <= _000_[4];
  assign state[4] = \state_reg[4] ;
  reg \state_reg[5] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[5]  <= _000_[5];
  assign state[5] = \state_reg[5] ;
  reg \state_reg[6] ;
  (* src = "ex4.v:7.5-10.8" *)
  always @(posedge clk)
      \state_reg[6]  <= _000_[6];
  assign state[6] = \state_reg[6] ;
  assign _000_[0] = 1'h0;
  assign change[0] = 1'h0;
  assign nextstate[0] = 1'h0;
  assign state[0] = 1'h0;
endmodule
